  common: &default_settings
    license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
    app_name: <%= ENV["NEW_RELIC_APPLICATION"] %>
    distributed_tracing:
      enabled: true
    agent_enabled: true
    log_level: info

  development:
    <<: *default_settings

  test:
    <<: *default_settings
    monitor_mode: false

  production:
    <<: *default_settings
